"""Add Playbook model

Revision ID: 2e105b0e566e
Revises: 
Create Date: 2025-03-04 22:01:49.527704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e105b0e566e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('contact_info', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('server_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dhcp_server_ip', sa.String(length=15), nullable=False),
    sa.Column('connection_type', sa.String(length=64), server_default='file', nullable=False),
    sa.Column('ssh_username', sa.String(length=64), nullable=True),
    sa.Column('ssh_password', sa.String(length=128), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('inventory_number', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_servers_ip_address'), ['ip_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_servers_mac_address'), ['mac_address'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_timestamp'), ['timestamp'], unique=False)

    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('starts', sa.DateTime(), nullable=True),
    sa.Column('ends', sa.DateTime(), nullable=True),
    sa.Column('binding_state', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('in_work', sa.Boolean(), nullable=True),
    sa.Column('taken_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_WORK', 'COMPLETED', 'BROKEN', 'PENDING', name='leasestatus'), server_default='active', nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leases_binding_state'), ['binding_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_ip'), ['ip'], unique=True)
        batch_op.create_index(batch_op.f('ix_leases_mac'), ['mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_taken_by_id'), ['taken_by_id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('lease_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('old_status', sa.Enum('ACTIVE', 'IN_WORK', 'COMPLETED', 'BROKEN', 'PENDING', name='leasestatus'), nullable=False),
    sa.Column('new_status', sa.Enum('ACTIVE', 'IN_WORK', 'COMPLETED', 'BROKEN', 'PENDING', name='leasestatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lease_status_history')
    op.drop_table('user_groups')
    op.drop_table('metrics')
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_taken_by_id'))
        batch_op.drop_index(batch_op.f('ix_leases_mac'))
        batch_op.drop_index(batch_op.f('ix_leases_ip'))
        batch_op.drop_index(batch_op.f('ix_leases_hostname'))
        batch_op.drop_index(batch_op.f('ix_leases_binding_state'))

    op.drop_table('leases')
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_timestamp'))

    op.drop_table('journal')
    op.drop_table('group_permissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_mac_address'))
        batch_op.drop_index(batch_op.f('ix_servers_ip_address'))
        batch_op.drop_index(batch_op.f('ix_servers_hostname'))

    op.drop_table('servers')
    op.drop_table('server_config')
    op.drop_table('playbooks')
    op.drop_table('permissions')
    op.drop_table('groups')
    op.drop_table('employees')
    # ### end Alembic commands ###
