"""Add status column to Lease

Revision ID: 8704028771bf
Revises: eef92f33a350
Create Date: 2025-02-24 22:17:41.570719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8704028771bf'
down_revision = 'eef92f33a350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), server_default='active', nullable=True)) #  Добавили server_default

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###