"""Initial migration

Revision ID: 89aecd4f2b45
Revises: 
Create Date: 2025-02-23 17:56:35.047011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aecd4f2b45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dhcp_server_ip', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('starts', sa.DateTime(), nullable=True),
    sa.Column('ends', sa.DateTime(), nullable=True),
    sa.Column('binding_state', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('in_work', sa.Boolean(), nullable=True),
    sa.Column('taken_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leases_binding_state'), ['binding_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_ip'), ['ip'], unique=True)
        batch_op.create_index(batch_op.f('ix_leases_mac'), ['mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_taken_by_id'), ['taken_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_taken_by_id'))
        batch_op.drop_index(batch_op.f('ix_leases_mac'))
        batch_op.drop_index(batch_op.f('ix_leases_ip'))
        batch_op.drop_index(batch_op.f('ix_leases_hostname'))
        batch_op.drop_index(batch_op.f('ix_leases_binding_state'))

    op.drop_table('leases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('server_config')
    # ### end Alembic commands ###
