"""Add connection_type to ServerConfig

Revision ID: eef92f33a350
Revises: fab9d21377bd
Create Date: 2025-02-23 21:46:30.679576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef92f33a350'
down_revision = 'fab9d21377bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('ssh_password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ssh_key_path', sa.String(length=255), nullable=True))
        #  ИСПРАВЛЕНИЕ: Добавляем server_default='file'
        batch_op.add_column(sa.Column('connection_type', sa.String(length=64), server_default='file', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_config', schema=None) as batch_op:
        batch_op.drop_column('connection_type')
        batch_op.drop_column('ssh_key_path')
        batch_op.drop_column('ssh_password')
        batch_op.drop_column('ssh_username')

    # ### end Alembic commands ###